
name: Development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  UnitTest:
  
    runs-on: ubuntu-latest
    
    timeout-minutes: 10
    
    steps:
    - name: "Checkout from Repository"
      uses: actions/checkout@v3
      
    - name: "Setup node"
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
        
    - name: "Install npm"
      run: npm i -g npm@latest
        
    - name: "Install dependencies" 
      uses: bahmutov/npm-install@v1
      
    - name: "Run Unit Test"
      run: npm run test --if-present
    
    - name: "Lint the code"
      run: npm run lint --if-present
      
  BuildImage:
   needs: UnitTest
   
   runs-on: ubuntu-latest
   
   steps:
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v2

   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
       username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
       password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

   - name: Build and push
     uses: docker/build-push-action@v4
     with:
       push: true
       tags: fauzancloud/open-sauced:alpha
      
  
    
      
