
name: development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    timeout-minutes: 10
    
    steps:
    - name: Checkout from Repository
      uses: actions/checkout@v3
      
    - name: "Setup node"
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
        
    - name: "Install npm"
      run: npm i -g npm@latest
        
    - name: "Install dependencies" 
      uses: bahmutov/npm-install@v1
      
    - name: "Run Unit Test"
      run: npm run test --if-present
    
    - name: "Lint the code"
      run: npm run lint --if-present
    
      
