
name: Development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  unitTest:
  
    runs-on: ubuntu-latest
    
    timeout-minutes: 10
    
    steps:
    - name: "Checkout from Repository"
      uses: actions/checkout@v3
      
    - name: "Setup node"
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
        
    - name: "Install npm"
      run: npm i -g npm@latest
        
    - name: "Install dependencies" 
      uses: bahmutov/npm-install@v1
      
    - name: "Run Unit Test"
      run: npm run test --if-present
    
    - name: "Lint the code"
      run: npm run lint --if-present
      
  BuildImage:
   needs: unitTest
   
   runs-on: ubuntu-latest
   
   steps:
   - name: "Build Docker"
     uses: bitovi/github-actions-docker-publish@v1.0.7
     with:
      checkout: true
      image_tag: alpha
      repo_name: fauzancloud/open-sauced
      docker_username: $DOCKER_REGISTRY_USERNAME
      docker_password: $DOCKER_REGISTRY_PASSWORD
      
  
    
      
